---
AWSTemplateFormatVersion: '2010-09-09'  
Description: S3 Bucket for a webapp
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 Bucket to create
  DomainName:
    Type: String
    Description: The name of the domain to use for the CloudFront distribution
  ACMCertificateArn:
    Type: String
    Description: The ARN of the ACM certificate to use for the CloudFront distribution
Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      BucketName:
        default: S3 Bucket Name

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          -
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 3
            NoncurrentVersionExpirationInDays: 3
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
  
  ##TODO   
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: Access S3 bucket content only through CloudFront

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Ref BucketName
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref ACMCertificateArn  
        Origins:
          - DomainName: !Sub ${BucketName}.s3-website.${AWS::Region}.amazonaws.com
            Id: CustomOrigin
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: CustomOrigin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
          MinTTL: 0
          DefaultTTL: 30
          MaxTTL: 30
          Compress: true
          ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03
        DefaultRootObject: index.html
        
#  Route53RecordSet:
#    Type: AWS::Route53::RecordSet
#    Properties:
#      HostedZoneName: !Sub '${RootDomainName}.'
#      Name: !Ref DomainName
#      Type: A
#      AliasTarget:
#        DNSName: !GetAtt CloudFrontDistribution.DomainName
#        EvaluateTargetHealth: false
#        HostedZoneId: Z2FDTNDATAQYW2
            
Outputs:
  S3Bucket:
    Value: !Ref S3Bucket
    Description: S3 Bucket for object storage
  CloudFrontDistribution:
    Value: !Ref CloudFrontDistribution
    Description: CloudFront Distribution

