AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Alarms and Metric Filters referencing individual files

Parameters:
  LogGroupName:
    Type: String
    Description: Name of the CloudWatch Log Group
  ForwardingLambdaArn:
    Type: String
    Description: The ARN of the Forwarding Lambda function
  
  # Alarm Enable/Disable Parameters
  EnableAccessDeniedAlarm:
    Type: String
    Description: Enable Access Denied alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableGetCallerIdentityAlarm:
    Type: String
    Description: Enable GetCallerIdentity alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableAttachUserPolicyAlarm:
    Type: String
    Description: Enable AttachUserPolicy alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableAuthenticateAlarm:
    Type: String
    Description: Enable Authenticate alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableCreateUserAlarm:
    Type: String
    Description: Enable CreateUser alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableDeleteUserAlarm:
    Type: String
    Description: Enable DeleteUser alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableIAMUserActivityAlarm:
    Type: String
    Description: Enable IAMUserActivity alarm
    Default: 'true'
    AllowedValues: ['true', 'false']

Conditions:
  CreateAccessDeniedAlarm: !Equals [!Ref EnableAccessDeniedAlarm, 'true']
  CreateGetCallerIdentityAlarm: !Equals [!Ref EnableGetCallerIdentityAlarm, 'true']
  CreateAttachUserPolicyAlarm: !Equals [!Ref EnableAttachUserPolicyAlarm, 'true']
  CreateAuthenticateAlarm: !Equals [!Ref EnableAuthenticateAlarm, 'true']
  CreateCreateUserAlarm: !Equals [!Ref EnableCreateUserAlarm, 'true']
  CreateDeleteUserAlarm: !Equals [!Ref EnableDeleteUserAlarm, 'true']
  CreateIAMUserActivityAlarm: !Equals [!Ref EnableIAMUserActivityAlarm, 'true']

Resources:
  AlarmAccessDenied:
    Type: AWS::CloudFormation::Stack
    Condition: CreateAccessDeniedAlarm
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/alarms/CW/AccessDenied.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !Ref ForwardingLambdaArn

  AlarmGetCallerIdentity:
    Type: AWS::CloudFormation::Stack
    Condition: CreateGetCallerIdentityAlarm
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/alarms/CW/GetCallerIdentity.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !Ref ForwardingLambdaArn

  AttachUserPolicy:
    Type: AWS::CloudFormation::Stack
    Condition: CreateAttachUserPolicyAlarm
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/alarms/CW/AttachUserPolicy.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !Ref ForwardingLambdaArn

  AlarmAuthenticate:
    Type: AWS::CloudFormation::Stack
    Condition: CreateAuthenticateAlarm
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/alarms/CW/Authenticate.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !Ref ForwardingLambdaArn

  AlarmCreateUser:
    Type: AWS::CloudFormation::Stack
    Condition: CreateCreateUserAlarm
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/alarms/CW/CreateUser.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !Ref ForwardingLambdaArn

  AlarmDeleteUser:
    Type: AWS::CloudFormation::Stack
    Condition: CreateDeleteUserAlarm
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/alarms/CW/DeleteUser.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !Ref ForwardingLambdaArn

  AlarmIAMUserActivity:
    Type: AWS::CloudFormation::Stack
    Condition: CreateIAMUserActivityAlarm
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/alarms/CW/IAMUserActivity.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !Ref ForwardingLambdaArn
    