AWSTemplateFormatVersion: '2010-09-09'
Description: Root template for nested stacks with Lambda code and environment variables

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Basic Configuration"
        Parameters:
          - EmailRecipient
          - LogGroupName
      - Label:
          default: "Alarm Configuration"
        Parameters:
          - EnableAccessDeniedAlarm
          - EnableGetCallerIdentityAlarm
          - EnableAttachUserPolicyAlarm
          - EnableAuthenticateAlarm
          - EnableCreateUserAlarm
          - EnableDeleteUserAlarm
          - EnableIAMUserActivityAlarm
    ParameterLabels:
      EmailRecipient:
        default: "📧 Email Recipient"
      LogGroupName:
        default: "📋 CloudWatch Log Group Name"
      EnableAccessDeniedAlarm:
        default: "🚫 Access Denied Events"
      EnableGetCallerIdentityAlarm:
        default: "🔍 GetCallerIdentity Events"
      EnableAttachUserPolicyAlarm:
        default: "📎 AttachUserPolicy Events"
      EnableAuthenticateAlarm:
        default: "🔐 SSO Authentication Events"
      EnableCreateUserAlarm:
        default: "👤 CreateUser Events"
      EnableDeleteUserAlarm:
        default: "🗑️ DeleteUser Events"
      EnableIAMUserActivityAlarm:
        default: "⚡ General IAM User Activity"

Parameters:
  EmailRecipient:
    Type: String
    Description: Email address to receive alarm notifications
  LogGroupName:
    Type: String
    Description: Name of the CloudWatch Log Group
    Default: aws-controltower/CloudTrailLogs
  
  # Alarm Enable/Disable Parameters
  EnableAccessDeniedAlarm:
    Type: String
    Description: Enable Access Denied alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableGetCallerIdentityAlarm:
    Type: String
    Description: Enable GetCallerIdentity alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableAttachUserPolicyAlarm:
    Type: String
    Description: Enable AttachUserPolicy alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableAuthenticateAlarm:
    Type: String
    Description: Enable Authenticate alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableCreateUserAlarm:
    Type: String
    Description: Enable CreateUser alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableDeleteUserAlarm:
    Type: String
    Description: Enable DeleteUser alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  EnableIAMUserActivityAlarm:
    Type: String
    Description: Enable IAMUserActivity alarm
    Default: 'true'
    AllowedValues: ['true', 'false']
  

Conditions:
  CreateAccessDeniedAlarm: !Equals [!Ref EnableAccessDeniedAlarm, 'true']
  CreateGetCallerIdentityAlarm: !Equals [!Ref EnableGetCallerIdentityAlarm, 'true']
  CreateAttachUserPolicyAlarm: !Equals [!Ref EnableAttachUserPolicyAlarm, 'true']
  CreateAuthenticateAlarm: !Equals [!Ref EnableAuthenticateAlarm, 'true']
  CreateCreateUserAlarm: !Equals [!Ref EnableCreateUserAlarm, 'true']
  CreateDeleteUserAlarm: !Equals [!Ref EnableDeleteUserAlarm, 'true']
  CreateIAMUserActivityAlarm: !Equals [!Ref EnableIAMUserActivityAlarm, 'true']

Resources:
  CloudWatchAlarmsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/CloudWatchAlarms.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !GetAtt ForwardingLambdaStack.Outputs.ForwardingLambdaArn
        EnableAccessDeniedAlarm: !Ref EnableAccessDeniedAlarm
        EnableGetCallerIdentityAlarm: !Ref EnableGetCallerIdentityAlarm
        EnableAttachUserPolicyAlarm: !Ref EnableAttachUserPolicyAlarm
        EnableAuthenticateAlarm: !Ref EnableAuthenticateAlarm
        EnableCreateUserAlarm: !Ref EnableCreateUserAlarm
        EnableDeleteUserAlarm: !Ref EnableDeleteUserAlarm
        EnableIAMUserActivityAlarm: !Ref EnableIAMUserActivityAlarm


  ForwardingLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/ForwardingLambda.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        EmailRecipient: !Ref EmailRecipient

Outputs:
  ForwardingLambdaArn:
    Description: ARN of the Forwarding Lambda function
    Value: !GetAtt ForwardingLambdaStack.Outputs.ForwardingLambdaArn
