AWSTemplateFormatVersion: '2010-09-09'
Description: Root template for nested stacks with Lambda code and environment variables

Parameters:
  LogGroupName:
    Type: String
    Description: Name of the CloudWatch Log Group
    Default: aws-controltower/CloudTrailLogs
  EmailRecipients:
    Type: CommaDelimitedList
    Description: Comma-separated list of email addresses to receive alarm notifications

Resources:
  CloudWatchAlarmsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/CloudWatchAlarms.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        ForwardingLambdaArn: !GetAtt ForwardingLambdaStack.Outputs.ForwardingLambdaArn

  ForwardingLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudwatcher-cloudformation-stage.s3.eu-central-1.amazonaws.com/templates/organisation/0.1/ForwardingLambda.yaml
      Parameters:
        LogGroupName: !Ref LogGroupName
        EmailRecipients: !Join [',', !Ref EmailRecipients]

Outputs:
  ForwardingLambdaArn:
    Description: ARN of the Forwarding Lambda function
    Value: !GetAtt ForwardingLambdaStack.Outputs.ForwardingLambdaArn
