name: Deploy Production

on:
  release:
    types: [published]

jobs:
  deploy-stage:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@customjs'

      # Setup AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID__PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY__PROD }}
          aws-region: eu-central-1
      - name: Install AWS CLI v2
        run:  |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

      # Run Cloudformation
      - name: Run cfn
        run: |
          aws cloudformation deploy \
          --stack-name cloudwatcher-cloudformation-prod \
          --template-file cloudformation.yml \
          --parameter-overrides \
              BucketName=cloudwatcher-cloudformation-prod \
              DomainName=cfn.cloudwatcher.io \
              RootDomainName=cloudwatcher.io \
              ACMCertificateArn=arn:aws:acm:us-east-1:819640458745:certificate/cc1700bd-4366-42f4-8f48-9ff3acc14f44 \
          --no-fail-on-empty-changeset

      # Create No Index Robots.txt
      - name: Create No Index Robots
        run: |
          cat > ./src/robots.txt << EOF
          User-agent: *
          Disallow: /
          EOF

      # Replace stage with prod in templates
      - name: Replace stage with prod in templates
        run: |
          find ./src/templates -type f -name "*.yaml" -exec sed -i 's/cloudwatcher-cloudformation-stage/cloudwatcher-cloudformation-prod/g' {} +

      # Upload To S3
      - name: Deploy to S3
        run: aws s3 cp --recursive ./src/ s3://cloudwatcher-cloudformation-prod/
          